server:
  port: 8080
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/ascend_test
    username: root
    password: P@ssw0rd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true